---
name: Kocom Wallpad with RS485 for 센트레빌 아스테리움 시그니처
version: 2023.08.013
slug: kocom_py
description: Kocom Wallpad for Home Assistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/vifrost/kocom.py
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/kocom/kocom.conf 설정파일: true
  share/kocom/kocom_main.py 실행파일: true
  share/kocom/device_parser.py 실행파일: true
  share/kocom/mqtt_handler.py 실행파일: true
  share/kocom/rs485.py 실행파일: true
  share/kocom/logger.py 실행파일: true
schema:
  share/kocom/kocom.conf 설정파일: bool
  share/kocom/kocom_main.py 실행파일: bool
  share/kocom/device_parser.py 실행파일: bool
  share/kocom/mqtt_handler.py 실행파일: bool
  share/kocom/rs485.py 실행파일: bool
  share/kocom/logger.py 실행파일: bool
